[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18" # Use whatever Node version you're developing with

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
